# Generated by Django 5.2.9 on 2026-01-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_listing_location_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(choices=[('Aroma', 'Awka'), ('Amansea', 'Amansea'), ('Ifite', 'Up School'), ('Ifite', 'Down School'), ('Temp Site', 'Awka'), ('OTHER', 'Other')], default='IFITE_ANAMBRA', max_length=100),
        ),
    ]
