# Generated by Django 5.2.9 on 2026-01-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_listing_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(choices=[('AROMA', 'Aroma'), ('AMANSEA', 'Amansea'), ('IFITE UP SCHOOL', 'Ifite Up School'), ('IFITE DOWN SCHOOL', 'Ifite Down School'), ('TEMP SITE', 'Temp Site'), ('OTHER', 'Other')], default='IFITE_ANAMBRA', max_length=100),
        ),
    ]
