# Generated by Django 5.2.9 on 2026-01-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_amenity_remove_listing_amenities_listing_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(db_column='price', decimal_places=2, max_digits=10),
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='first_price',
        ),
        migrations.AddField(
            model_name='listing',
            name='year_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
