# Generated by Django 5.2.9 on 2026-01-06 14:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_listing_images_listingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
